# -*- coding: utf-8 -*-
"""metodosnum.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1p1frPrWujPtyVUL4RY_QnVQxEVESLGBl
"""

"""**Ejercicio 1**"""
import numpy as np
import matplotlib.pyplot as plt

# Datos de ejemplo
x = np.array([5, 10, 15, 20, 25])
y = np.array([0.6, 1.2, 1.9, 2.5, 3.1])

# Cálculo de los coeficientes
n = len(x)
sum_x = np.sum(x)
sum_y = np.sum(y)
sum_xy = np.sum(x * y)
sum_x2 = np.sum(x**2)

# Fórmulas de regresión lineal
b = (n * sum_xy - sum_x * sum_y) / (n * sum_x2 - sum_x**2)
a = (sum_y - b * sum_x) / n

print(f"Coeficientes de la regresión:")
print(f"a (pendiente) = {a:.4f}")
print(f"b (intercepto) = {b:.4f}")

# Predicción usando el modelo
y_pred = a + b * x

# Gráfica
plt.figure(figsize=(8,6))
plt.plot(x, y, 'o', label='Datos')
plt.plot(x, y_pred, '-', label=f'Ajuste lineal: y = {a:.2f} + {b:.2f}x', color='red')
plt.xlabel('x')
plt.ylabel('y')
plt.title('Regresión Lineal')
plt.legend()
plt.grid(True)
plt.savefig('regresion_lineal.png', dpi=300)  # Guarda la figura
plt.show()



"""**Ejercicio 2**"""
import numpy as np
import matplotlib.pyplot as plt

# Datos de ejemplo
x = np.array([0, 2, 4, 6, 8])
y = np.array([100, 92, 85, 78, 71])

# Cálculo de los coeficientes
n = len(x)
sum_x = np.sum(x)
sum_y = np.sum(y)
sum_xy = np.sum(x * y)
sum_x2 = np.sum(x**2)

# Fórmulas de regresión lineal
b = (n * sum_xy - sum_x * sum_y) / (n * sum_x2 - sum_x**2)
a = (sum_y - b * sum_x) / n

print(f"Coeficientes de la regresión:")
print(f"a (pendiente) = {a:.4f}")
print(f"b (intercepto) = {b:.4f}")

# Predicción usando el modelo
y_pred = a + b * x

# Gráfica
plt.figure(figsize=(8,6))
plt.plot(x, y, 'o', label='Datos')
plt.plot(x, y_pred, '-', label=f'Ajuste lineal: y = {a:.2f} + {b:.2f}x', color='red')
plt.xlabel('x')
plt.ylabel('y')
plt.title('Regresión Lineal')
plt.legend()
plt.grid(True)
plt.savefig('regresion_lineal.png', dpi=300)  # Guarda la figura
plt.show()



"""**Ejercicio 3**"""
import numpy as np
import matplotlib.pyplot as plt

# Datos de ejemplo
x = np.array([50, 70, 90, 110, 130])
y = np.array([15, 21, 27, 33, 39])

# Cálculo de los coeficientes
n = len(x)
sum_x = np.sum(x)
sum_y = np.sum(y)
sum_xy = np.sum(x * y)
sum_x2 = np.sum(x**2)

# Fórmulas de regresión lineal
b = (n * sum_xy - sum_x * sum_y) / (n * sum_x2 - sum_x**2)
a = (sum_y - b * sum_x) / n

print(f"Coeficientes de la regresión:")
print(f"a (pendiente) = {a:.4f}")
print(f"b (intercepto) = {b:.4f}")

# Predicción usando el modelo
y_pred = a + b * x

# Gráfica
plt.figure(figsize=(8,6))
plt.plot(x, y, 'o', label='Datos')
plt.plot(x, y_pred, '-', label=f'Ajuste lineal: y = {a:.2f} + {b:.2f}x', color='red')
plt.xlabel('x')
plt.ylabel('y')
plt.title('Regresión Lineal')
plt.legend()
plt.grid(True)
plt.savefig('regresion_lineal.png', dpi=300)  # Guarda la figura
plt.show()